include ./makedefs

#定义编译命令相关
SHELL = sh
CC = $(TCHAIN_PREFIX)-gcc
CPP = $(TCHAIN_PREFIX)-g++
AR = $(TCHAIN_PREFIX)-ar
LD = $(TCHAIN_PREFIX)-ld
OBJCOPY = $(TCHAIN_PREFIX)-objcopy
OBJDUMP = $(TCHAIN_PREFIX)-objdump
SIZE = $(TCHAIN_PREFIX)-size
NM = $(TCHAIN_PREFIX)-nm
COPY = cp
REMOVE_CMD = rm
REMOVE = $(REMOVE_CMD) -f
FLASH_TOOL = openocd



#中断向量表地址
#
VECTOR_TABLE_LOCATION =


#链接脚本的目录
#
LINKERSCRIPTPATH = .


#调试格式
#
#DEBUG = stabs
#DEBUG = dwarf-2

#C额外的定义
#
CDEFS = -DPART_${PART} -Dgcc -DLOADER

#ASM额外的定义
#
ADEFS = _D__ASSEMBLY__

#编译标准
#


#如果定义了额外的中断向量表
ifdef VECTOR_TABLE_LOCATION
CDEFS += -D$(VECTOR_TABLE_LOCATION)
ADEFS += -D$(VECTOR_TABLE_LOCATION)
endif

CDEFS += -D$(RUN_MODE) -D$(CHIP)
ADEFS += -D$(RUN_MODE) -D$(CHIP)



#定义CFLAGS
CFLAGS = -mthumb
CFLAGS += -mcpu=$(MCU)
CFLAGS += -O$(OPT)
CFLAGS += -ffunction-sections
CFLAGS += -fdata-sections
CFLAGS += -pedantic
CFLAGS += -DPART_${PART}
CFLAGS += -Dgcc -DLOADER
CFLAGS += -D$(RUN_MODE) -D$(CHIP)
CFLAGS += -Wall
CFLAGS += $(CDEFS)
CFLAGS += $(patsubst %,-I%,$(IPATH)) -I.
CFLAGS += -MD
#CFLAGS += -DTARGET_IS_TEMPEST_RB1
CFLAGS += -DUART_BUFFERED -DTARGET_IS_DUSTDEVIL_RA0
#CFLAGS += ${patsubst %,-I%,${subst :, ,${IPATH}}} -I.
#CFLAGS += -Wa,-adhlns=$(addprefix $(OUTDIR)/, $(notdir $(addsuffix .lst, $(basename $<))))
#CFLAGS += -MP -MF $(OUTDIR)/dep/$(@F).d


#other cflags
CFLAGS += ${CFLAGSgcc}

ifdef DEBUG
CFLAGS += -g -D DEBUG
endif

#flags only for C
CONLYFLAGS += -std=c99


#定义CPPFLAGS
CPPFLAGS = -fno-rtti -fno-exceptions
CPPFLAGS += 

#定义ASFLAGS
ASFLAGS = -mthumb
ASFLAGS += -mcpu=$(MCU)
ASFLAGS += -MD
ASFLAGS += ${patsubst %,-I%,${subst :, ,${IPATH}}}
#ASFLAGS += $(patsubst %,-I%,$(IPATH))
ASFLAGS += -I. -x assembler-with-cpp
ASFLAGS += _D__ASSEMBLY__ -D$(VECTOR_TABLE_LOCATION) -D$(RUN_MODE) -D$(CHIP)
ASFLAGS += -Wa,-adhlns=$(addprefix $(OUTDIR)/, $(notdir $(addsuffix .lst, $(basename $<))))
ASFLAGS += -Wa,-g$(DEBUG)

ASFLAGS += $(ADEFS)

LIBGCC=${shell ${CC} ${CFLAGS} -print-libgcc-file-name}
LIBC=${shell ${CC} ${CFLAGS} -print-file-name=libc.a}
LIBM=${shell ${CC} ${CFLAGS} -print-file-name=libm.a}

MATH_LIB = -lm

LDFLAGS = -nostartfiles -Wl,-Map=$(OUTDIR)/$(TARGET).map,--cref,--gc-sections
LDFLAGS += $(patsubst %,-L%,$(EXTRA_LIBDIRS))
#LDFLAGS += $(patsubst %,-l%,$(EXTRA_LIBS))

LDFLAGS += $(CPLUSPLUS_LIB)

LDFLAGS = --gc-sections
#LDFLAGS += $(MATH_LIB)
#LDFLAGS += -lc
#如果是内存调试
ifeq ($(RUN_MODE),RAM_RUN)
LDFLAGS +=-T$(LINKERSCRIPTPATH)/${CPART}-ram.ld --entry ResetHandler
else 
LDFLAGS +=-T$(LINKERSCRIPTPATH)/${CPART}-rom.ld --entry ResetHandler
endif


#OPENOCD设置
OOCD_LOADFILE+=$(OUTDIR)/$(TARGET).axf
OOCD_EXE=openocd
OOCD_CL=-d0
OOCD_CL+=-f interface/openocd-usb.cfg -f board/stm32f10x_128k_eval.cfg
OOCD_CL+=-c init -c targets
OOCD_CL+=-c "halt"
OOCD_CL+=-c "flash write_image erase $(OOCD_LOADFILE)" -c "verify_image $(OOCD_LOADFILE)"
OOCD_CL+=-c "reset run"
OOCD_CL+=-c shutdown




# List of all source files.
ALLSRC = $(ASRC) $(SRC) $(CPPSRC)
ALLSRCBASE = $(notdir $(basename $(ALLSRC)))
ALLOBJ  = $(addprefix $(OUTDIR)/, $(addsuffix .o, $(ALLSRCBASE)))

LSTFILES = $(addprefix $(OUTDIR)/, $(addsuffix .lst, $(ALLSRCBASE)))
DEPFILES = $(addprefix $(OUTDIR)/dep/, $(addsuffix .o.d, $(ALLSRCBASE)))


#编译从这里开始
all: begin gccversion build sizeafter end

begin:
	@echo -e "\033[43;30m -------- begin (mode: $(RUN_MODE)) --------\033[0m"

#显示编译器的版本号
gccversion : 
	@echo -e "\033[47;32m GCC version: \033[0m"
	@$(CC) --version

#设置编译目标文件格式
ifeq ($(LOADFORMAT),ihex)
build: axf hex lss sym
else 
ifeq ($(LOADFORMAT),binary)
build: axf bin lss sym
else 
ifeq ($(LOADFORMAT),both)
build: axf hex bin lss sym
else 
$(error "$(MSG_FORMATERROR) $(FORMAT)")
endif
endif
endif

#显示最后目标文件占用的rom和ram
sizeafter:
	@echo -e "\033[43;30m Size after build:\033[0m"
	$(SIZE) -A -x $(OUTDIR)/$(TARGET).axf

end:
	@echo -e "\033[43;30m --------  end  --------\033[0m"



axf: $(OUTDIR)/$(TARGET).axf
	@if [ -f  $(TARGET).axf ]; then echo ;else $(COPY) $(OUTDIR)/$(TARGET).axf ./; fi
lss: $(OUTDIR)/$(TARGET).lss 
sym: $(OUTDIR)/$(TARGET).sym
hex: $(OUTDIR)/$(TARGET).hex
bin: $(OUTDIR)/$(TARGET).bin



#生成hex文件
%.hex: %.axf
	@echo -e "\033[43;30mCreating load file:\033[0m" $@
	$(OBJCOPY) -O ihex $< $@
	
#生成bin文件
%.bin: %.axf
	@echo -e "\033[43;30mCreating load file:\033[0m" $@
	$(OBJCOPY) -O binary $< $@

#生成反汇编文件
# using objdump testing: option -C
%.lss: %.axf
	@echo -e "\033[43;30mCreating Extended Listing/Disassembly:\033[0m" $@
	$(OBJDUMP) -h -S -C -r $< > $@

#生成符号表
%.sym: %.axf
	@echo -e "\033[43;30mCreating Symbol Table:\033[0m" $@
	$(NM) -n $< > $@

# Link: create ELF output file from object files.
.SECONDARY : $(TARGET).axf
.PRECIOUS : $(ALLOBJ)



%.axf:  $(ALLOBJ)
	@echo
	@echo -e "\033[43;30m Linking :\033[0m" $@
	$(LD) $(LDFLAGS) $(ALLOBJ) $(LIBA) --output $@  ${LIBC} ${LIBM} ${LIBGCC}
#	$(CC) $(CFLAGS) $(CONLYFLAGS) $(ALLOBJ) $(LIBA) --output $@ $(LDFLAGS)
#	$(CPP) $(THUMB) $(CFLAGS) $(ALLOBJ) --output $@ $(LDFLAGS)



#直接将固件编程到单片机上,待修改
program: $(TARGET).elf
	@echo "\033[43;30mProgramming with OPENOCD\033[0m"
	$(OOCD_EXE) $(OOCD_CL)


#由汇编文件生成目标文件
define ASSEMBLE_TEMPLATE
$(OUTDIR)/$(notdir $(basename $(1))).o : $(1)
	@echo -e "\033[43;30mAssembling:\033[0m" $$< "->" $$@
	$(CC) -c $(THUMB) $$(ASFLAGS) $$< -o $$@ 
endef
$(foreach src, $(ASRC), $(eval $(call ASSEMBLE_TEMPLATE, $(src)))) 

#由c文件生成目标文件
define COMPILE_C_TEMPLATE
$(OUTDIR)/$(notdir $(basename $(1))).o : $(1)
	@echo -e "\033[43;30m Compiling C :\033[0m" $$< "->" $$@
	$(CC) -c $(CFLAGS) $(CONLYFLAGS) $$< -o $$@ 
endef
$(foreach src, $(SRC), $(eval $(call COMPILE_C_TEMPLATE, $(src)))) 


#由cpp文件生成目标文件
define COMPILE_CPP_TEMPLATE
$(OUTDIR)/$(notdir $(basename $(1))).o : $(1)
	@echo -e "\033[43;30m Compiling C++ :\033[0m" $$< "->" $$@
	$(CC) -c $(THUMB) $$(CFLAGS) $$(CPPFLAGS) $$< -o $$@ 
endef
$(foreach src, $(CPPSRC), $(eval $(call COMPILE_CPP_TEMPLATE, $(src)))) 



# Compile: create assembler files from C source files. ARM/Thumb
$(SRC:.c=.s) : %.s : %.c
	@echo -e "\033[43;30mCreating asm-File from C-Source:\033[0m" $< to $@
	$(CC) $(THUMB) -S $(CFLAGS) $(CONLYFLAGS) $< -o $@

# Target: clean project.
clean: begin clean_list end

clean_list :
	@echo $(MSG_CLEANING)
	$(REMOVE) $(OUTDIR)/$(TARGET).map
	$(REMOVE) $(OUTDIR)/$(TARGET).axf
	$(REMOVE) $(OUTDIR)/$(TARGET).hex
	$(REMOVE) $(OUTDIR)/$(TARGET).bin
	$(REMOVE) $(OUTDIR)/$(TARGET).sym
	$(REMOVE) $(OUTDIR)/$(TARGET).lss
	$(REMOVE) $(ALLOBJ)
	$(REMOVE) $(LSTFILES)
	$(REMOVE) $(DEPFILES)
	$(REMOVE) $(SRC:.c=.s)
	$(REMOVE) $(SRCARM:.c=.s)
	$(REMOVE) $(CPPSRC:.cpp=.s)
	$(REMOVE) $(CPPSRCARM:.cpp=.s)
	$(REMOVE) $(TARGET).axf
	$(REMOVE) -r gcc


# Create output files directory
$(shell mkdir $(OUTDIR) 2>/dev/null)

# Include the dependency files.
-include $(shell mkdir $(OUTDIR)/dep 2>/dev/null) $(wildcard $(OUTDIR)/dep/*)

# Listing of phony targets.
.PHONY : all begin finish end sizeafter gccversion \
build axf hex bin lss sym clean clean_list program
