######################################################################
# Automatically generated by qmake (2.01a) Thu Sep 3 13:52:20 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
