/**************************************************************************************************************
Create Date:	2006-11-10 11:09
Name:			Luquan
Version:		1.0
Note:

**************************************************************************************************************/
#ifndef __LCD_Parameter_H__
#define __LCD_Parameter_H__

/*-------------------------------------------------------------------------------------------------------------
		LCD²ÎÊý
-------------------------------------------------------------------------------------------------------------*/
#define LCD_Dot      		240			//0xf0
#define LCD_Line     		320			//0x0140
#define LCD_Pels			0x12C00
#define IC_Code	    		0x9320

#define Address_Set1		0x21		//Vertical GRAM Address Set
#define Address_Set2		0x20		//Horizontal GRAM Address Set
#define DataWrite_Start		0x22

#endif
